### ISSUE TITLE
Username/password authentication is deprecated

### ISSUE THREAD

**Issue by AndrewEckart** [aronwc/ghc-utils#1]
* ghc-utils version: 
* Python version: 3.7
* Operating System: Ubuntu 18.04

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I followed the instructions in the README. The command worked the first time, but I received a deprecation notice via email:

![image](https://user-images.githubusercontent.com/5485577/94714180-68a67980-0311-11eb-8255-3504b74787f2.png)

The second time I ran the command, it threw: 
```
github3.exceptions.AuthenticationFailed: 401 Bad credentials. The API can't be accessed using username/password authentication. Please create a personal access token to access this endpoint: http://github.com/settings/tokens
```

Proposed fix is to support token-based authentication.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

Command:
`ghc-utils grades -u AndrewEckart -p ******** -o UChicago-MPCS -a mpcs-55001-fall-2020-hw1 -s students.txt -g grades.csv`

Output:
```
getting grades
Traceback (most recent call last):
  File "/home/andrew/.local/bin/ghc-utils", line 8, in <module>
    sys.exit(main())
  File "/home/andrew/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/andrew/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/andrew/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrew/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrew/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/andrew/.local/lib/python3.7/site-packages/ghc_utils/cli.py", line 34, in grades
    repo = gh.repository(organization, '%s-%s' % (assignment_prefix, student))
  File "/home/andrew/.local/lib/python3.7/site-packages/github3/github.py", line 1981, in repository
    json = self._json(self._get(url), 200)
  File "/home/andrew/.local/lib/python3.7/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.AuthenticationFailed: 401 Bad credentials. The API can't be accessed using username/password authentication. Please create a personal access token to access this endpoint: http://github.com/settings/tokens
```

**Comment by AndrewEckart** [comment]
This is actually fairly easy to resolve. It turns out that GitHub Personal Access Tokens can be passed directly to the password field instead of a password.

No change is needed, except perhaps to the README.

**Comment by aronwc** [comment]
Thanks, @AndrewEckart should be fixed now (note, I've changed the flag from -p to -t).
